import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  currentQuestion: 1,
  questions: {
    1: {
      question: "Pick A Color",
      choose: {
        "click1.1": "./quizPics/citron_crested.jpg",
        "click1.2": "./quizPics/major_mitchell.jpg",
        "click1.3": "./quizPics/pink_and_grey2.jpg",
        "click1.4": "./quizPics/red_tailed_black.jpg",
      },
    },
    2: {
      question: "question2",
      choose: {
        "click2.1": "./quizPics/red_tailed_black.jpg",
        "click2.2": "./quizPics/citron_crested.jpg",
        "click2.3": "./quizPics/pink_and_grey2.jpg",
        "click2.4": "./quizPics/major_mitchell.jpg",
      },
    },
  },
  answers: {},
};

export const quizSlice = createSlice({
  name: 'quiz',
  initialState,
  reducers: {
    saveAnswer: (state, action) => {
      state.answers[action.payload.questionNumber] = action.payload.answer;
    },
    incrementQuestion: (state) => {
      state.currentQuestion += 1;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { saveAnswer, incrementQuestion } = quizSlice.actions;

export const selectQuizQuestions = (state) => state.quiz.questions;
export const selectQuizAnswers = (state) => state.quiz.answers;
export const selectQuizCurrentQuestion = (state) => state.quiz.currentQuestion;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = () => (dispatch, getState) => {
  const currentValue = selectQuizCurrentQuestion(getState());
  if (currentValue % 2 === 1) {
    dispatch(incrementQuestion());
  };
};

export default quizSlice.reducer;
